root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ./cmd/api/main.go"
  delay = 1000
  exclude_dir = ["tmp", "vendor", "testutil", "tests", "migrations"]
  exclude_regex = ["_test.go"]
  include_ext = ["go"]
  kill_delay = "2s"
  stop_on_error = true

[misc]
  clean_on_exit = true
